### ISSUE TITLE
Freezes and reboots

### ISSUE THREAD

**Issue by dariusz-goc** [spakkkk/SKIZO-chiron#6]
I experience freezes and reboots because of default overclocking. Sometimes it freezes right after entering the pattern before the kernel configuration kicks in. I suggest the overclocking was a option, not the default state. Also FSync is disabled by default, it corrupted my data and reset my system settings after a couple of reboots, thank God for twrp backup... I suggest you enable fsync by default.

**Comment by rakbladsvalsen** [comment]
@dariusz-goc Perhaps it's only you experiencing these issues. I mean, I did experience freezes but only the first 2-3 reboots if I tried to unlock immediately. I am using simple_ondemand as GPU governor and so far this kernel is smooth as butter. 

As far as I know fsync has some performance impact since all the data has to be written first to disk. This might cause latency, so it's better to leave it disabled (and yeah, I've never had problems with fsync disabled). I'm pretty sure there's something wrong on your side.

By the way, it would be nice if you could provide a semi-detailed changelolg, @spakkkk . The telegram description doesn't say a lot :( 
Anyway, thanks for the kernel. 

(MI6, LOS 15.1).

**Comment by spakkkk** [comment]
really thanks for answering @possessedbysatan

last releases, since 001 (cleaned and rebased release), the changes are minimal, that's why i didn't post any changelog... tgram have a pinned post about features

btw i will make overclock optional in next releases

thanks for all feedback and for using the kernel 
I will close the "issue"

**Comment by dariusz-goc** [comment]
Hello folks,

Obviously I don't mean to be disrespectful or anything, but this is an issue I feel very strongly about. Your kernel @spakkkk is exceptional, very fast indeed, that's why I would wish for it to be free of any unnecessary problems.

It is true that "(...) fsync has some performance impact since all the data has to be written first to disk.".
However it should be always enabled during boot. Otherwise it might work for a while, but eventually it will freeze at the wrong time during writing some important data and when at that time it's not written to the disk it's gonna cause issues. I tried many kernels on many devices and I always had issues with fsync disabled, sooner or later. Corrupted data partition, system data, or total reset of Android settings as was the case with your kernel. Fsync can be disabled in the kernel management app if you feel lucky, but that kicks in after the boot, otherwise we have no protection against the corruption during boot. From experience I can't anymore use a kernel with fsync disabled by default and I would advice anyone against it.

**Comment by rakbladsvalsen** [comment]
@dariusz-goc 
I get your point, and while most of the things you say are true, probably most people (including me) have never had any problem related to FSync. 

Speaking for myself, I don't see why the system partition would get corrupted (it's usually mounted as read-only since there's little to no I/O activity). Probably it's the way you use your phone, pal (/system doesn't get corrupted that easy). Most Linux distros (or at least the major ones) have FSync disabled just because caching all the stuff is faster than flushing everything to disk immediately. Sure, there might be a data loss if the computer goes offline unexpectedly, but does that ever happen in a phone? 

Cheers.

**Comment by dariusz-goc** [comment]
I didn't say that system partition gets corrupted. I said:
- data partition (as a whole)
- system data (which is a part of data partition and is located on data partition)
or
- system settings (which are certain databases on data partition)

"it's the way you use your phone, pal"

You mean booting the phone, unlocking with pattern, the phone freezing due to overclocking and getting data corruption from that? That's a special use case now?

"Sure, there might be a data loss if the computer goes offline unexpectedly, but does that ever happen in a phone?"

Yes, when it freezes unexpectedly because of overclocking. I happened to me several times on this kernel before the fatal data corruption. Try some processing intensive tasks. Maybe you barely use your phone or your processor is from the pile that better handles overclocking (you know not all of the same processors are created equal, right? They're within a spec, but differ on the borderlines of it.)

**Comment by spakkkk** [comment]
I have to agree, every chipset is different even if the SOC is the same.
In my case, per example, it works good.

Undervolting + Overclocking can be too dangerous for some chipsets, and its totally random.

Like i said, next release i will remove overclock by default and activate fsync - just in case.

Thanks for reporting!

**Comment by dariusz-goc** [comment]
Thank you for your thoughtful consideration! I wish you best of luck!
